// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/cart.tsx";
import * as $1 from "./routes/index.tsx";
import * as $2 from "./routes/restaurant/[name].tsx";
import * as $$0 from "./islands/Cart.tsx";
import * as $$1 from "./islands/Header.tsx";
import * as $$2 from "./islands/Product.tsx";

const manifest = {
  routes: {
    "./routes/cart.tsx": $0,
    "./routes/index.tsx": $1,
    "./routes/restaurant/[name].tsx": $2,
  },
  islands: {
    "./islands/Cart.tsx": $$0,
    "./islands/Header.tsx": $$1,
    "./islands/Product.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
